name: Build and Publish on Maven

on:
  push:
    tags:
      - '*'

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            reqwest-jni
      - run: cargo install cross
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          check-latest: true
          cache: "gradle"
      - name: Run Build
        run: ./gradlew publish
        env:
          USERNAME: ${{ secrets.MAVEN_USERNAME }}
          PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
